## Exercise 1:
What range of indices do your get with :-1 ? Be careful!

You get the last column!! 

## Exercise 2:


In [1]:
from numpy import array, matrix, zeros, random, linalg

A = matrix(random.rand(3,3))
A

matrix([[ 0.52152103,  0.99144951,  0.04075274],
        [ 0.9756034 ,  0.08359366,  0.86994669],
        [ 0.10994968,  0.48752431,  0.85044137]])

In [5]:
## We are going to choose x to make sure we solve properly later. 
x_given = matrix(random.rand(3,1))
print("x is \n",x_given)
b = A.dot(x_given)
print()
print("b is \n",b)

x is 
 [[ 0.30157691]
 [ 0.75480264]
 [ 0.23255927]]

b is 
 [[ 0.91510483]
 [ 0.55963034]
 [ 0.59892095]]


In [9]:
Ab = matrix(zeros((3,4)))
Ab[:,:3]= A
Ab[:,3]= b
print("Ab is \n",Ab)

Ab is 
 [[ 0.52152103  0.99144951  0.04075274  0.91510483]
 [ 0.9756034   0.08359366  0.86994669  0.55963034]
 [ 0.10994968  0.48752431  0.85044137  0.59892095]]


In [10]:
print("Ab is initially")
print(Ab)
m = Ab[1,0]/Ab[0,0]
print("The row multiplier is m = ", m)
Ab[1,:] = Ab[1,:] - m * Ab[0,:]
print("Ab is now")
print(Ab)

m = Ab[2,0]/Ab[0,0]
print("The row multiplier is m = ", m)
Ab[2,:] = Ab[2,:] - m * Ab[0,:]
print("Ab is now")
print(Ab)

m = Ab[2,1]/Ab[1,1]
print("The row multiplier is m = ", m)
Ab[2,1:] = Ab[2,1:] - m * Ab[1,1:]
print("Ab is now")
print(Ab)



Ab is initially
[[ 0.52152103  0.99144951  0.04075274  0.91510483]
 [ 0.9756034   0.08359366  0.86994669  0.55963034]
 [ 0.10994968  0.48752431  0.85044137  0.59892095]]
The row multiplier is m =  1.87068851455
Ab is now
[[ 0.52152103  0.99144951  0.04075274  0.91510483]
 [ 0.         -1.77109955  0.79371101 -1.15224576]
 [ 0.10994968  0.48752431  0.85044137  0.59892095]]
The row multiplier is m =  0.21082502125
Ab is now
[[ 0.52152103  0.99144951  0.04075274  0.91510483]
 [ 0.         -1.77109955  0.79371101 -1.15224576]
 [ 0.          0.27850195  0.84184968  0.40599395]]
The row multiplier is m =  -0.157248048307
Ab is now
[[ 0.52152103  0.99144951  0.04075274  0.91510483]
 [ 0.         -1.77109955  0.79371101 -1.15224576]
 [ 0.          0.          0.96665918  0.22480556]]


In [11]:
A_mat = matrix(A)
b_mat = matrix(b)
A_inverse = A_mat.I
print("The inverse of A is ")
print(A_inverse)
x = A_inverse.dot(b)
print("The solution is")
print(x)

The inverse of A is 
[[ 0.39538645  0.92208477 -0.96217999]
 [ 0.82211657 -0.49172036  0.4636028 ]
 [-0.52240453  0.16267165  1.03449077]]
The solution is
[[ 0.30157691]
 [ 0.75480264]
 [ 0.23255927]]


In [12]:
x = linalg.solve(A_mat,b_mat)
print("Using the numpy solve function we get")
print(x)

Using the numpy solve function we get
[[ 0.30157691]
 [ 0.75480264]
 [ 0.23255927]]
