# Math 246 Unit 9: Random numbers, and a simple example of simulation

### Brenton LeMesurier,  Thursday November 19, 2015

Random numbers are often useful both for simulation of physical processes and for generating a coleciot of test cases.
Here we will do a mathematical simulation: approximating $pi$ on the basis that the unit circle occupies a fraction $pi/4$ of the $2 \times 2$ square enclosing it.

Actualy, the best we can do is *pseudo-random* numbers generatd by algorithms that actual produce a very long but eventual repaeig sequence of numbers.

## Module random within package numpy

The pseudo-random nyber generator we use are provided by package numpy in its module random – full name `numpy.random`.
We introduce the abbreviation "npr" for this, along with the standard abbreviation "np" for numpy:

In [1]:
import numpy as np
import numpy.random as npr

This module contains numerous random number generators; here we look at just a few.

## Uniformly distributed real numbers: `numpy.random.rand`

First, the function `rand` (full name `numpy.random.rand`) generates uniformly diatributed real numbers in the interval $[0,1)$.
To generate a single value, use it with no argument:

In [2]:
n_samples = 4
for sample in range(n_samples):
    print(npr.rand())

0.5831761011474371
0.3778295131961672
0.44280821200807174
0.9003075432407449


To generate an array of values all at once, one can specify how many as the first and only:

In [3]:
numbers = npr.rand(n_samples)
print(numbers)

[ 0.74267463  0.54546167  0.08777314  0.53571539]


We can also generate multi-dimensional arrays, by giving the lengths of each dimension as arguments:

In [4]:
numbers2d = npr.rand(2,3)
print('A two-dimensional array of random numbers:\n', numbers2d)
numbers3d = npr.rand(2,3,4)
print('A three-dimensional array of random numbers:\n', numbers3d)

A two-dimensional array of random numbers:
 [[ 0.23777286  0.71211757  0.19658881]
 [ 0.28332012  0.49456663  0.47288411]]
A three-dimensional array of random numbers:
 [[[ 0.02047323  0.2334306   0.62500741  0.69325521]
  [ 0.14212129  0.22734591  0.19409425  0.08587863]
  [ 0.32504998  0.18291458  0.69300375  0.67766151]]

 [[ 0.52398229  0.83594288  0.44910537  0.05114869]
  [ 0.87640731  0.45032081  0.91731495  0.51147435]
  [ 0.0593191   0.01292466  0.04085691  0.9711921 ]]]


## Normally distributed real numbers: `numpy.random.randn`

The function `randn` has the same interface, but generates numbers with the standard normal distribution of mean zero, standard deviation one:

In [5]:
print('Ten normally distributed values:\n', npr.randn(20))

Ten normally distributed values:
 [ 0.92128705 -0.286562   -0.12959645  0.57011152  0.01806076  2.42976356
  0.73431243  1.63968914 -0.02817224  0.03978772  0.48766957 -1.46185991
  0.62866372 -0.7982065  -0.47764834 -0.81671435 -0.98416506 -1.30884743
  0.8151803   0.90770292]


In [6]:
n_samples = 10**7
normf_samples = npr.randn(n_samples)
mean = sum(normf_samples)/n_samples
print('The mean of these', n_samples, 'samples is', mean)
standard_deviation = np.sqrt((sum(normf_samples**2) - mean**2)/n_samples)
print('and their standard deviation is', standard_deviation)

The mean of these 10000000 samples is -0.000509452243552
and their standard deviation is 1.00011049891


## Random integers: `numpy.random.random_integers`

One can generate integers, uniformly distributed betwen specified lower and upper values:

In [7]:
n_dice = 60
dice_rolls = npr.random_integers(1, 6, n_dice)
print(n_dice, 'random dice rolls:\n', dice_rolls)
# Count each outcome: this needs a list instead of an array:
dice_rolls_list = list(dice_rolls)
for value in (1, 2, 3, 4, 5, 6):
    count = dice_rolls_list.count(value)
    print(value, 'occured', count, 'times')

60 random dice rolls:
 [4 1 6 2 3 3 1 2 2 2 3 3 2 5 2 2 2 1 4 2 3 2 3 2 1 3 4 4 3 3 5 5 6 2 4 5 2
 5 1 2 1 4 4 6 2 5 3 1 4 5 4 2 4 5 2 3 4 6 4 6]
1 occured 7 times
2 occured 17 times
3 occured 11 times
4 occured 12 times
5 occured 8 times
6 occured 5 times


/Users/crhea/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:2: DeprecationWarning: This function is deprecated. Please call randint(1, 6 + 1) instead
  from ipykernel import kernelapp as app


Things average out with more rolls:

In [8]:
n_dice = 10**6
dice_rolls = npr.random_integers(1, 6, n_dice)
# Count each outcome: this needs a list instead of an array:
dice_rolls_list = list(dice_rolls)
for value in (1, 2, 3, 4, 5, 6):
    count = dice_rolls_list.count(value)
    print(value, 'occured a fraction', count/n_dice, 'of the time')

/Users/crhea/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:2: DeprecationWarning: This function is deprecated. Please call randint(1, 6 + 1) instead
  from ipykernel import kernelapp as app


1 occured a fraction 0.167377 of the time
2 occured a fraction 0.166986 of the time
3 occured a fraction 0.166364 of the time
4 occured a fraction 0.166966 of the time
5 occured a fraction 0.165416 of the time
6 occured a fraction 0.166891 of the time


# Exercise

Approximate $\pi$ as follows:
- generate a long list of random points in the square $[-1,1] \times [-1,1]$ that circumscribes the unit circle,
by genrating succwssive random values for both the $x$ and $y$ coordinates.
- compute the fraction of these that are inside the unit circle, which should be approximately $\pi/4$.
- Multiply by four and ther you are!

Hint: it takes a lot of samples to get decent accuracy, so experiment with successively more of them.

Also, repeat the trial several times with each choice of number of samples, to see the variation in accuracy.