# Math 246 Unit 8: Numpy matrices and linear algebra

### Brenton LeMesurier,  October 29, 2015

## Introduction

The module `numpy` (and this also module `pylab`) has a variable type `matrix`
which is a specialization of the type `array` that makes some linear algebra operation easier.
Matrices are always two dimensional, so to use type `matrix` for a vector `v` and be able to do matrix-vector multiplication with `A * v`, the vector needs to be created as a matrix with a single column.

This module shows how to create and use numpy matrices, with an exercise on row reduction.

### Floating pont numbers vs integers

Thoug Python is generally good at understanding that an integer lke `7` is to be used as a floating point (real) number, it is sometimes best ot make this distinction explicitly when working with module `numpy`; otherwise sometimes division doen within numpy functions return an integer answer, like `7/2 = 3`.

This fomr now on, when I men an nteger to be used as a floating point number, I give it a decimal point" `7./2.` wil realiably be `3.5`

First the usual boilerplate, including import of all the numpy functions to be used below.

In [2]:
'''
Unit 8: Numpy matrices
Author: Brenton LeMesurier, <lemesurierb@cofc.edu>
Date: October 29, 2015
'''
from numpy import array, matrix, zeros

## Creating numpy matrices

The methods that work for creating array also work, with an obvious change:

In [3]:
# Create an array from a list:
Aarray = array([[1., 2.], [3., 4.]])
print(Aarray)

[[ 1.  2.]
 [ 3.  4.]]


In [4]:
# Create a matrix from a 2D list:
A = matrix([[1., 2.], [3., 4.]])
print(A)

[[ 1.  2.]
 [ 3.  4.]]


One can convert back and forth

In [5]:
Barray = array([[0., 1.], [1., 0.]])
# Create a matrix from a 2D array:
B = matrix(Barray)
print(B)

[[ 0.  1.]
 [ 1.  0.]]


What's the difference? For one thing, multiplication works differently:

Array multiplication multiplies the corresponding elements:

In [6]:
print(Aarray * Barray)

[[ 0.  2.]
 [ 3.  0.]]


Matrix multiplication instead does the expected mathematical thing:

In [7]:
print(A * B)

[[ 2.  1.]
 [ 4.  3.]]


Arrays can be multiplied "mathematically" by using the `.dot()` method, which extnds the idea of the dot produnt of two vectors: it computes the array of all the dot products of each combination of a row of the first array with a column of the second:

In [8]:
print(Aarray.dot(Barray))

[[ 2.  1.]
 [ 4.  3.]]


## More options for matrix creation
Matrices can also be created directly without using lists or arrays,
using a string with semicolons separating the rows.
(Matlab users should recognize this notation!)

In [9]:
C = matrix("3., 4. 5.; 6., 7., 8.")
print(C)

[[ 3.  4.  5.]
 [ 6.  7.  8.]]


The commas within a row are optional – but I recommend that you be consistent, not like in this example:

In [10]:
D = matrix("6. 5. 4.; 1., 5. -2.")
print(D)

[[ 6.  5.  4.]
 [ 1.  5. -2.]]


Row and column matrices are different, and best created with this new notation:

In [11]:
brow = matrix('2. 4. 10.')
print(brow)

[[  2.   4.  10.]]


In [12]:
bcol = matrix('2. ; 4. ; 10.')
print(bcol)

[[  2.]
 [  4.]
 [ 10.]]


The difference is important for matrix-vector multiplication:

In [13]:
# 2x3 matrix times 3x1 (column) matrix gives a 2x1 column matrix:
print(C * bcol)

[[  72.]
 [ 120.]]


In [14]:
# 2x3 matrix time 1x3 (row) matrix gives an error!:
print(C * brow)

ValueError: shapes (2,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

## Other matrix operations: transposes, inverses, etc.

In [15]:
print("C is:")
print(C)
print("Its transpose C.T is:")
print(C.T)

C is:
[[ 3.  4.  5.]
 [ 6.  7.  8.]]
Its transpose C.T is:
[[ 3.  6.]
 [ 4.  7.]
 [ 5.  8.]]


In [16]:
print("A is:")
print(A)
Ainverse = A.I
print("Its inverse is:")
print(Ainverse)
print("Check by multiplying, both ways:")
print(A * Ainverse)
print(Ainverse * A)

A is:
[[ 1.  2.]
 [ 3.  4.]]
Its inverse is:
[[-2.   1. ]
 [ 1.5 -0.5]]
Check by multiplying, both ways:
[[  1.00000000e+00   0.00000000e+00]
 [  8.88178420e-16   1.00000000e+00]]
[[  1.00000000e+00   0.00000000e+00]
 [  1.11022302e-16   1.00000000e+00]]


## *Slicing*: Extracting rows, columns, and other rectangular chunks from matrices

This works with lists, arrays and matrices, and we have seen some of it before;
I review it here because it will help with doing row operations on matrices.

### Index notation for slicing

For an index with n possible values, from 0 to n-1:

- `a:b` means indices i, $a \leq i < b$

- `a:` is short for `a:n`, so indices $a \leq i$, all the way to the maximum index value 
- `:b` is short for `0:b`, so all indices $i < b$
- `:` combines both of the above, so is short for `0:n`, all possible indices
- index value `-1` refers the last entry; the same as index n-1
- index value `-m` refers the "m-th last" entry; the same as index n-m

## Exercise 1

What range of indices do your get with `:-1` ?
Be careful!

In [17]:
Ab = C.copy()  # Make a copy of C under a new name.
print("The 'augmented matrix' Ab is:")
print(Ab)

The 'augmented matrix' Ab is:
[[ 3.  4.  5.]
 [ 6.  7.  8.]]


In [18]:
row1 = Ab[0,:]
print("Its first row (index 0!) is:")
print(row1)

Its first row (index 0!) is:
[[ 3.  4.  5.]]


In [19]:
column2 = Ab[:,1]
print("Its second column (index 1!) is:")
print(column2)

Its second column (index 1!) is:
[[ 4.]
 [ 7.]]


In [ ]:
A = Ab[:,:2]
print("Its left-hand 2x2 chunk is the square matrix:")
print(A)

In [1]:
b = Ab[:,-1]  # Index -1 means last value of the index
print("Its right-hand column is the column matrix:")
print(b)

NameError: name 'Ab' is not defined

In [ ]:
print("We can also combine matrices (and arrays) into a larger one:")
A_and_b = zeros((2,3))  # First, create an empty shell of a matrix
'''Note well: we always have to specify ranges of index values in the matrix where
we are inserting stuff, even when a range contains just a single index value:
'''
print(A_and_b)
A_and_b[0:2,0:2] = A
print(A_and_b)
A_and_b[0:2,2:] = b  
print(A_and_b)

## Row operations and row reduction

We can extract a row of a matrix, and so we can use this to do row operations.
The above augmented matrix Ab can be row reduced to "row echelon form".
Only one operation is needed:

In [ ]:
Ab = C.copy()  # Reset Ab in case it has been changed!
print("Ab is initially")
print(Ab)
m = Ab[1,0]/Ab[0,0]
print("The row multiplier is m = ", m)
Ab[1,:] = Ab[1,:] - m * Ab[0,:]
print("Ab is now")
print(Ab)

## Exercise 2

This can be done either by modifying this notebook, or copying the relevant code from here into a Python file `Unit7.py` and adding stuff there.
I describe the "notebook" option.

Add a code cell below this one, and then in that cell:

1. Create a 3x3 matrix A (You could explore the function `rand` from module `numpy.random` or function `hilbert` from module `scipy.linalg`)
2. Create a 3 element column matrix b
3. Combine these into the augmented matrix Ab
4. Do the row operations (three in all) needed to put the augmented matrix into row-echelon form.
As above, print each multiplier, and print each updated version of the matrix.
5. Compute (and display) the inverse of A, and use this to solve $Ax = b$ for x.
6. Read about the numpy function `solve`, and use this to solve for x the easy way.